# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ProTabula
sub_title: Real-Time Communication for Real-Time Behavior.
company: ProTabula LLC
email: info@protabula.com
description:  ProTabula is a real-time communication solution that allows for quick feedback between staff about behavior as students progress through the support continuum.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.protabula.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: [ .vscode, package.json, node_modules, gulpfile.js]

collections:
  featurettes:
    output: false
  teasers:
    output: false
  cards:
    output: false
    
